const GET_FRACTAL_SUCCESS = 'GET_FRACTAL_SUCCESS';
const SAVE_FRACTAL_SUCCESS = 'SAVE_FRACTAL_SUCCESS';
const RESET_SETTINGS = 'RESET_SETTINGS';

export default {
  GET_FRACTAL_SUCCESS,
  SAVE_FRACTAL_SUCCESS,
  RESET_SETTINGS,
};
