const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';
const NO_USERNAME = 'NO_USERNAME';
const CREATED_USERNAME_SUCCESS = 'CREATED_USERNAME_SUCCESS';
const CREATED_USERNAME_FAIL = 'CREATED_USERNAME_FAIL';
const RESET_USERNAME_REQUEST = 'RESET_USERNAME_REQUEST';

export default {
  GOOGLE_SIGN_IN,
  NO_USERNAME,
  CREATED_USERNAME_SUCCESS,
  CREATED_USERNAME_FAIL,
  RESET_USERNAME_REQUEST,
};